version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - /tmp:/tmp
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - transcribe-network

  celery:
    build: ./backend
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - /tmp:/tmp
    command: celery -A tasks.celery_app worker --loglevel=info
    networks:
      - transcribe-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - transcribe-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    networks:
      - transcribe-network

networks:
  transcribe-network:
    driver: bridge