steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/transcribe-api:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/transcribe-api:latest'
    - './backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/transcribe-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/transcribe-api:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'transcribe-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/transcribe-api:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'

images:
- 'gcr.io/$PROJECT_ID/transcribe-api:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/transcribe-api:latest'